#!/usr/bin/env bash
set -o pipefail  # trace ERR through pipes
set -o errtrace  # trace ERR through 'time command' and other functions
set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
set -o errexit   ## set -e : exit the script if any statement returns a non-true return value

MAGICK_BASE=${MAGICK_BASE-"/apps/nuxeo/pkg/bin"}
MAGICK_OPTS=${MAGICK_OPTS-"-quiet"}
MAGICK_LOG=${MAGICK_LOG="/tmp/magick.log"}

calledas=$(basename "$0")

# if this script is called as "magicenv" 
# then set up symbolic links for all imagemagick commands
if [[ "$calledas" == "magickenv" ]]; then
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # http://stackoverflow.com/questions/59895
  cd $DIR
  for magick in animate compare composite conjure convert display identify import mogrify montage stream 
  do
    ln -s magickenv $magick;
  done
  exit
fi
# otherwise I'm not being called as "magickenv" so I must be a wrapper
# execute imagemagick command and log it, adding extra opts
set +e
$MAGICK_BASE/$calledas $MAGICK_OPTS "$@"
R=$?
{
  echo "MAGICK: $MAGICK_BASE/$calledas $MAGICK_OPTS $@"
  echo "MAGICK-WRAPPER exit code $R"
} >>$MAGICK_LOG 2>&1
exit $R
